// Generated by scripts/build-discovery.py from the Protex Discovery Assessment sheet.
// Do not edit by hand: change the sheet and re-run the script.

import type { Persona, Question, CloseEvidence } from './types.ts';

export const STAGES = [
  "Discovery",
  "Deep Dive",
  "Vendor Selection",
  "Vendor of Choice",
  "Legal & Procurement"
] as const;

export const STATUS_OPTIONS = [
  {
    "label": "Not discussed",
    "value": "not_discussed"
  },
  {
    "label": "Touched on",
    "value": "touched_on"
  },
  {
    "label": "Answered",
    "value": "answered"
  },
  {
    "label": "Confirmed",
    "value": "confirmed"
  }
] as const;

export const WHO_DETAIL_VALUES = {
  "ops": "an_operations_or_plant_leader_engaged",
  "it": "it_or_ot_engaged",
  "vp": "someone_vp_or_above_engaged"
} as const;

export const QUESTIONS: Question[] = [
  {
    "n": 1,
    "topic": "The operation",
    "question": "Which sites are in scope, and what happens on them?",
    "why": "Sets the size of the deal and the risk profile before you ask anything harder. Single small sites lose more often.",
    "whoToAsk": [
      "Site EHS manager",
      "Ops or plant leader"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_sites_status",
    "detailsProperty": "da_sites_details",
    "properties": [
      "da_sites_status",
      "da_sites_notes",
      "da_sites_source",
      "da_sites_details",
      "number_of_sites"
    ],
    "details": [
      {
        "label": "Number of sites, named, with country",
        "value": "number_of_sites_named_with_country"
      },
      {
        "label": "What each site does (production, DC, cross-dock, store back-of-house)",
        "value": "what_each_site_does_production_dc_cross_dock_store_back_of_house"
      },
      {
        "label": "Headcount per site, and the share that is agency or seasonal",
        "value": "headcount_per_site_and_the_share_that_is_agency_or_seasonal"
      },
      {
        "label": "Shift pattern and weekend or night working",
        "value": "shift_pattern_and_weekend_or_night_working"
      },
      {
        "label": "Vehicle fleet by type (forklifts, reach trucks, AGVs, HGV movements)",
        "value": "vehicle_fleet_by_type_forklifts_reach_trucks_agvs_hgv_movements"
      },
      {
        "label": "Contractors or third parties on site",
        "value": "contractors_or_third_parties_on_site"
      },
      {
        "label": "[M] Continuous or discrete production; lines or cells in scope",
        "value": "m_continuous_or_discrete_production_lines_or_cells_in_scope"
      },
      {
        "label": "[L] Client contracts per site and renewal dates",
        "value": "l_client_contracts_per_site_and_renewal_dates"
      },
      {
        "label": "[R] DCs only, or back-of-house in stores too",
        "value": "r_dcs_only_or_back_of_house_in_stores_too"
      }
    ],
    "ways": {
      "open": [
        "Walk me through a typical shift, from the gate to the dock.",
        "Which sites would you want this to cover first, and what makes those different?"
      ],
      "label": [
        "It sounds like the sites run quite differently from each other."
      ],
      "noOriented": [
        "Would it be wrong to start with the sites that worry you most rather than all of them?"
      ],
      "mirror": [
        "They say \"it's mostly the busy sites\" → \"The busy sites?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So it's six sites, four running nights, and agency labour peaks in Q4. Have I got that right?"
      ]
    },
    "listenFor": "A count and names, not 'multi-site'. Nights and agency labour are where risk usually concentrates.",
    "redFlag": "Only one small site, or no site count after two calls. Deals of $40–80K are the worst-converting band.",
    "whyClose": "Win-Loss: under-scoped multi-site deals ($40–80K) win 8.9% in new business."
  },
  {
    "n": 2,
    "topic": "The operation",
    "question": "Where is the risk, and how much of it can they actually see today?",
    "why": "The gap between where the risk is and what anyone sees is the reason Protex exists. It also tells you where cameras go.",
    "whoToAsk": [
      "Site EHS manager",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_risk_status",
    "detailsProperty": "da_risk_details",
    "properties": [
      "da_risk_status",
      "da_risk_notes",
      "da_risk_source",
      "da_risk_details",
      "da_risk_self_rated_floor_visibility"
    ],
    "details": [
      {
        "label": "Highest-risk areas, named by the buyer",
        "value": "highest_risk_areas_named_by_the_buyer"
      },
      {
        "label": "Their own estimate of how much of the floor they see (most / about half / under a quarter)",
        "value": "their_own_estimate_of_how_much_of_the_floor_they_see_most_about_half_under_a_qua"
      },
      {
        "label": "Share of a shift that site walks and observations actually cover",
        "value": "share_of_a_shift_that_site_walks_and_observations_actually_cover"
      },
      {
        "label": "Observation programme: how many are required vs actually done",
        "value": "observation_programme_how_many_are_required_vs_actually_done"
      },
      {
        "label": "What happens on nights and weekends when safety isn't there",
        "value": "what_happens_on_nights_and_weekends_when_safety_isn_t_there"
      }
    ],
    "ways": {
      "open": [
        "Where on site are you most worried someone gets hurt?",
        "Would you say you have visibility into most of your operations, about half, or less than that?",
        "Picture that area right now. How would you know what's happening there if you can't be there?"
      ],
      "label": [
        "It seems like nights are a bit of a blind spot.",
        "It sounds like the walks happen, but they can't be everywhere."
      ],
      "noOriented": [
        "Is it unfair to say most of what happens on the floor never gets seen by anyone in safety?"
      ],
      "mirror": [
        "They say \"we cover it with walks\" → \"With walks?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So you see maybe half the floor, the dock at shift change is the worry, and nights depend on whoever's supervising. That's where it is?"
      ]
    },
    "listenFor": "A band they chose themselves. 89% of 18 EHS and ops leaders surveyed see half or less of their floor in time to act. Typical coverage: safety staff on site about 19% of the year.",
    "redFlag": "'We see everything' with no evidence: they're unaware there's a problem, so expect a long cycle. They can't name a worst area: they've never measured it.",
    "whyClose": ""
  },
  {
    "n": 3,
    "topic": "The operation",
    "question": "What do they measure and report today?",
    "why": "The baseline every business case is measured against. Without it there is no 'before'.",
    "whoToAsk": [
      "Site EHS manager",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_measure_status",
    "detailsProperty": "da_measure_details",
    "properties": [
      "da_measure_status",
      "da_measure_notes",
      "da_measure_source",
      "da_measure_details",
      "da_measure_recordable_lost_time_rate_latest",
      "da_measure_near_misses_reported_per_month"
    ],
    "details": [
      {
        "label": "Recordable or lost-time rates by site for the last two years (TRIR, LTIFR, RIDDOR)",
        "value": "recordable_or_lost_time_rates_by_site_for_the_last_two_years_trir_ltifr_riddor"
      },
      {
        "label": "Serious-injury-potential events per year",
        "value": "serious_injury_potential_events_per_year"
      },
      {
        "label": "Near misses reported per month, and their guess at how many go unreported",
        "value": "near_misses_reported_per_month_and_their_guess_at_how_many_go_unreported"
      },
      {
        "label": "Leading indicators they track, and where each number comes from",
        "value": "leading_indicators_they_track_and_where_each_number_comes_from"
      },
      {
        "label": "EHS system that holds incidents and actions (Enablon, Intelex, Cority, Sphera, EcoOnline…)",
        "value": "ehs_system_that_holds_incidents_and_actions_enablon_intelex_cority_sphera_ecoonl"
      },
      {
        "label": "[M] Certifications held and next audit date",
        "value": "m_certifications_held_and_next_audit_date"
      },
      {
        "label": "[L] Safety KPIs clients hold them to",
        "value": "l_safety_kpis_clients_hold_them_to"
      },
      {
        "label": "[R] Injury mix and the share that is manual handling",
        "value": "r_injury_mix_and_the_share_that_is_manual_handling"
      }
    ],
    "ways": {
      "open": [
        "What does your board or leadership team actually look at each month?",
        "How many near misses get reported in a month, and what share do you think never gets written down?"
      ],
      "label": [
        "It sounds like the numbers you report are the lagging ones.",
        "It seems like near-miss reporting depends a lot on who's on shift."
      ],
      "noOriented": [
        "Would it be wrong to say the near-miss number is lower than reality?"
      ],
      "mirror": [
        "They say \"our numbers are pretty good\" → \"Pretty good?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So recordables are flat at about 2.1, near misses are around 40 a month, and you think the real number is double. That's right?"
      ]
    },
    "listenFor": "Numbers by site, not a group average. 'Probably 50 percent or more of our incidents go unreported' (EHS lead, Bunzl).",
    "redFlag": "Only a group-level rate. A low near-miss count read as good news.",
    "whyClose": "HubSpot: incident baseline filled on 1 of 43 wins since Oct 2024."
  },
  {
    "n": 4,
    "topic": "The operation",
    "question": "What happens after something is found?",
    "why": "Tells you whether they can act on what we surface. Buyers name capacity, not detection, as what holds them back.",
    "whoToAsk": [
      "Site EHS manager",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_after_status",
    "detailsProperty": "da_after_details",
    "properties": [
      "da_after_status",
      "da_after_notes",
      "da_after_source",
      "da_after_details",
      "da_after_open_corrective_actions",
      "da_after_reviewer_hours_per_week"
    ],
    "details": [
      {
        "label": "Where corrective actions are logged, and how many are open",
        "value": "where_corrective_actions_are_logged_and_how_many_are_open"
      },
      {
        "label": "How closure is checked: does anyone verify the fix worked?",
        "value": "how_closure_is_checked_does_anyone_verify_the_fix_worked"
      },
      {
        "label": "Who would review what the system finds, and how many hours a week they really have",
        "value": "who_would_review_what_the_system_finds_and_how_many_hours_a_week_they_really_hav"
      },
      {
        "label": "How findings reach the people who can change the process",
        "value": "how_findings_reach_the_people_who_can_change_the_process"
      }
    ],
    "ways": {
      "open": [
        "When you put a control in last quarter, how did you know it worked?",
        "Who would look at what this finds, and when in their week would they do it?"
      ],
      "label": [
        "It sounds like finding things isn't the problem. Getting them fixed is.",
        "It seems like the team is already stretched."
      ],
      "noOriented": [
        "Is it unrealistic to expect your team to review another feed every day?"
      ],
      "mirror": [
        "They say \"we close them out eventually\" → \"Eventually?\""
      ],
      "accusationAudit": [
        "You might be thinking this is just going to create more work for a team that's already flat out."
      ],
      "summary": [
        "So actions live in a spreadsheet, nobody checks whether they stuck, and the one person who'd review this has maybe two hours a week. That's the reality?"
      ]
    },
    "listenFor": "A named reviewer and hours per week. 'We have the data. We just don't have the capacity to analyze it in time' (Compleat Food).",
    "redFlag": "'No one is making corrective action at this time.' That's an accountability problem, not ours. Also a red flag: 'The team will find time.'",
    "whyClose": "Corrective actions not closing came up at 34 accounts in 2026 call digests."
  },
  {
    "n": 5,
    "topic": "The operation",
    "question": "What does an incident cost the line?",
    "why": "In manufacturing the throughput number usually dwarfs claim cost, and it's the one that reaches a COO.",
    "whoToAsk": [
      "Ops or plant leader",
      "Finance or risk"
    ],
    "industry": "M",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_money_m_status",
    "detailsProperty": "da_money_m_details",
    "properties": [
      "da_money_m_status",
      "da_money_m_notes",
      "da_money_m_source",
      "da_money_m_details"
    ],
    "details": [
      {
        "label": "Cost per hour of downtime, or the productivity measure they use instead",
        "value": "cost_per_hour_of_downtime_or_the_productivity_measure_they_use_instead"
      },
      {
        "label": "Insurance or captive cost charged to the plant",
        "value": "insurance_or_captive_cost_charged_to_the_plant"
      },
      {
        "label": "Open regulator notices, recent inspections or fines",
        "value": "open_regulator_notices_recent_inspections_or_fines"
      },
      {
        "label": "High-energy exposures beyond vehicles: guarding, LOTO, cranes, confined space, hot work",
        "value": "high_energy_exposures_beyond_vehicles_guarding_loto_cranes_confined_space_hot_wo"
      }
    ],
    "ways": {
      "open": [
        "What does a stoppage cost you, in output rather than claims?",
        "How does insurance cost get charged back to the plant?"
      ],
      "label": [
        "It sounds like a single stoppage hurts the schedule more than the claim does."
      ],
      "noOriented": [
        "Would you be against putting a number on what an hour of downtime costs?"
      ],
      "mirror": [
        "They say \"it's expensive when it stops\" → \"Expensive?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So an hour down costs you around £18k and the plant carries part of the group premium. That's right?"
      ]
    },
    "listenFor": "Their own basis (cost per hour or a productivity percentage). Don't impose ours.",
    "redFlag": "Nobody in Operations will share the number: the case stays a safety case.",
    "whyClose": "Ops or plant leader on 48% of wins vs 19% of losses."
  },
  {
    "n": 6,
    "topic": "The operation",
    "question": "What's riding on client contracts?",
    "why": "In 3PL the case is contract retention, so contract value and renewal dates are the numbers that matter.",
    "whoToAsk": [
      "Ops or plant leader",
      "Finance or risk"
    ],
    "industry": "L",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_money_l_status",
    "detailsProperty": "da_money_l_details",
    "properties": [
      "da_money_l_status",
      "da_money_l_notes",
      "da_money_l_source",
      "da_money_l_details"
    ],
    "details": [
      {
        "label": "Contract value per site and in total",
        "value": "contract_value_per_site_and_in_total"
      },
      {
        "label": "Renewal dates and tender calendar",
        "value": "renewal_dates_and_tender_calendar"
      },
      {
        "label": "Safety penalty or exit clauses, and how much safety weighs in tenders",
        "value": "safety_penalty_or_exit_clauses_and_how_much_safety_weighs_in_tenders"
      },
      {
        "label": "Margin per unit, and how much of it goes on insurance",
        "value": "margin_per_unit_and_how_much_of_it_goes_on_insurance"
      }
    ],
    "ways": {
      "open": [
        "Which client contracts run through these sites, and when does each come up?",
        "How much does safety count when you tender?"
      ],
      "label": [
        "It sounds like your safety numbers end up in front of clients at QBRs."
      ],
      "noOriented": [
        "Would it be a stretch to say one bad incident could cost you a renewal?"
      ],
      "mirror": [
        "They say \"clients are asking more about safety\" → \"Asking more?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So two contracts renew next year, safety is scored in the tender, and insurance eats a visible slice of margin. Is that it?"
      ]
    },
    "listenFor": "A renewal date is often the real deadline. Penalty clauses turn 'clients care about safety' into a number.",
    "redFlag": "Cameras owned by the landlord or client, and that owner can't approve this.",
    "whyClose": ""
  },
  {
    "n": 7,
    "topic": "The operation",
    "question": "What do claims and turnover cost?",
    "why": "In retail, manual-handling claims usually dominate cost, and risk management often holds the budget.",
    "whoToAsk": [
      "Finance or risk",
      "Group EHS lead"
    ],
    "industry": "R",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_money_r_status",
    "detailsProperty": "da_money_r_details",
    "properties": [
      "da_money_r_status",
      "da_money_r_notes",
      "da_money_r_source",
      "da_money_r_details"
    ],
    "details": [
      {
        "label": "Claims per year and average cost by injury type, manual handling separated",
        "value": "claims_per_year_and_average_cost_by_injury_type_manual_handling_separated"
      },
      {
        "label": "Premium or self-insured, deductible, loss ratio",
        "value": "premium_or_self_insured_deductible_loss_ratio"
      },
      {
        "label": "Cost per hire and annual turnover cost",
        "value": "cost_per_hire_and_annual_turnover_cost"
      },
      {
        "label": "Share of claims litigated",
        "value": "share_of_claims_litigated"
      },
      {
        "label": "Peak-season injury spike",
        "value": "peak_season_injury_spike"
      }
    ],
    "ways": {
      "open": [
        "How many claims a year, and what does the average manual-handling claim cost?",
        "What has the broker said is driving premium?"
      ],
      "label": [
        "It seems like peak is when most of the claims start."
      ],
      "noOriented": [
        "Is it a bad idea to look at claim cost by injury type before anything else?"
      ],
      "mirror": [
        "They say \"MSD is the big one\" → \"The big one?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So manual handling is over half your claim cost, averages about $28k, and peak doubles it. That's right?"
      ]
    },
    "listenFor": "Manual handling separated out. Self-insured means every avoided claim is cash.",
    "redFlag": "No claims breakdown available, and nobody from risk involved.",
    "whyClose": ""
  },
  {
    "n": 8,
    "topic": "Cameras & infrastructure",
    "question": "Do their cameras see the risk?",
    "why": "Camera estates kill more deals than competitors. Find out early whether this is a licence conversation or a capital works one.",
    "whoToAsk": [
      "IT / OT",
      "Security or camera owner"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      1,
      2,
      2,
      3
    ],
    "statusProperty": "da_cameras_status",
    "detailsProperty": "da_cameras_details",
    "properties": [
      "da_cameras_status",
      "da_cameras_notes",
      "da_cameras_source",
      "da_cameras_details",
      "number_of_cameras"
    ],
    "details": [
      {
        "label": "Cameras per site, and how many face the floor rather than gates and fences",
        "value": "cameras_per_site_and_how_many_face_the_floor_rather_than_gates_and_fences"
      },
      {
        "label": "Make, model and resolution; analogue vs IP",
        "value": "make_model_and_resolution_analogue_vs_ip"
      },
      {
        "label": "Which of the named risk areas are covered, and which aren't",
        "value": "which_of_the_named_risk_areas_are_covered_and_which_aren_t"
      },
      {
        "label": "Recording system (VMS or NVR) and whether we can get a stream",
        "value": "recording_system_vms_or_nvr_and_whether_we_can_get_a_stream"
      }
    ],
    "ways": {
      "open": [
        "How many cameras are on each site, and what are they pointed at?",
        "Which of the areas you mentioned does a camera actually cover today?"
      ],
      "label": [
        "It sounds like the cameras went in for security, not for the floor."
      ],
      "noOriented": [
        "Would it be wrong to assume some of those cameras are older analogue ones?"
      ],
      "mirror": [
        "They say \"we've got cameras everywhere\" → \"Everywhere?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So about 40 cameras per site, mostly IP, but the dock and the yard aren't covered. Is that right?"
      ]
    },
    "listenFor": "Roughly 1080p at 8–10 fps on the risk areas. Camera coverage gaps came up at 61 accounts in 2026.",
    "redFlag": "Entrance and fence-line cameras only. An analogue or banned estate means capital works first.",
    "whyClose": ""
  },
  {
    "n": 9,
    "topic": "Cameras & infrastructure",
    "question": "Who owns the cameras and the network?",
    "why": "If someone else owns the estate, they can stop the deal however good the case is.",
    "whoToAsk": [
      "Security or camera owner",
      "IT / OT"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      2,
      3
    ],
    "statusProperty": "da_owner_status",
    "detailsProperty": "da_owner_details",
    "properties": [
      "da_owner_status",
      "da_owner_notes",
      "da_owner_source",
      "da_owner_details",
      "da_owner_camera_owner"
    ],
    "details": [
      {
        "label": "Who owns the cameras: us, Security, the landlord or the client",
        "value": "who_owns_the_cameras_us_security_the_landlord_or_the_client"
      },
      {
        "label": "What they were installed for",
        "value": "what_they_were_installed_for"
      },
      {
        "label": "Network: bandwidth, how IT and OT are separated, rack space and power on site",
        "value": "network_bandwidth_how_it_and_ot_are_separated_rack_space_and_power_on_site"
      },
      {
        "label": "Camera refresh cycle and whose capital pays for it",
        "value": "camera_refresh_cycle_and_whose_capital_pays_for_it"
      }
    ],
    "ways": {
      "open": [
        "Who owns the cameras, and what were they put in for?",
        "What would the camera owner need to see to say yes to this?"
      ],
      "label": [
        "It sounds like Security has the final say on those cameras."
      ],
      "noOriented": [
        "Would Security be against us using the existing streams?"
      ],
      "mirror": [
        "They say \"Security manages all that\" → \"Manages all that?\""
      ],
      "accusationAudit": [
        "You may be expecting Security to see this as someone else touching their cameras."
      ],
      "summary": [
        "So Security owns the estate, it was bought for theft, and nobody has asked them about safety use yet. That's right?"
      ]
    },
    "listenFor": "Security owns or controls the cameras at 23 accounts in 2026. 'Do not want us to tap into their cameras' (FedEx EU).",
    "redFlag": "A landlord or client owns the estate and can't approve the change.",
    "whyClose": ""
  },
  {
    "n": 10,
    "topic": "Cameras & infrastructure",
    "question": "What will IT, security and data rules require?",
    "why": "IT, security or AI-governance approval was the gate at 89 accounts. IT on the deal is the sharpest sign of a win.",
    "whoToAsk": [
      "IT / OT"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      1,
      2,
      2,
      3
    ],
    "statusProperty": "da_rules_status",
    "detailsProperty": "da_rules_details",
    "properties": [
      "da_rules_status",
      "da_rules_notes",
      "da_rules_source",
      "da_rules_details"
    ],
    "details": [
      {
        "label": "Security review and how long it takes",
        "value": "security_review_and_how_long_it_takes"
      },
      {
        "label": "AI committee or AI policy, and whether anything is frozen",
        "value": "ai_committee_or_ai_policy_and_whether_anything_is_frozen"
      },
      {
        "label": "Cloud rules (AWS, Azure) and where data must stay",
        "value": "cloud_rules_aws_azure_and_where_data_must_stay"
      },
      {
        "label": "Footage retention and who may view it",
        "value": "footage_retention_and_who_may_view_it"
      },
      {
        "label": "Whether processing must stay on site",
        "value": "whether_processing_must_stay_on_site"
      }
    ],
    "ways": {
      "open": [
        "What does a new vendor go through with your security team, and how long does it usually take?",
        "How are AI tools approved here right now?"
      ],
      "label": [
        "It sounds like AI tools are getting extra scrutiny at the moment."
      ],
      "noOriented": [
        "Is it too early to get your security team's questions in front of us?"
      ],
      "mirror": [
        "They say \"there's a new AI council\" → \"A new AI council?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So security review is about six weeks, there's an AI committee that meets monthly, and data has to stay in the EU. That's the path?"
      ]
    },
    "listenFor": "IT was on 34% of wins vs 6% of losses (six times more likely). Get them in before the pilot.",
    "redFlag": "A new AI council or AI freeze (Weir). Cloud mismatch (Eaton lost over AWS vs Azure). 'Video cannot leave our network' (Fuyao).",
    "whyClose": "IT engaged: 6x more common on wins (Win-Loss)."
  },
  {
    "n": 11,
    "topic": "The problem",
    "question": "What is actually going wrong, in their words?",
    "why": "The problem has to be theirs, said by them. One we recognised from our own research doesn't count.",
    "whoToAsk": [
      "Site EHS manager",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_problem_status",
    "detailsProperty": "da_problem_details",
    "properties": [
      "da_problem_status",
      "da_problem_notes",
      "da_problem_source",
      "da_problem_details"
    ],
    "details": [
      {
        "label": "Which process is failing: vehicles near people, PPE or procedure, actions not closing, ergonomics, seeing the floor, near-miss reporting, reporting for leadership, contractors",
        "value": "which_process_is_failing_vehicles_near_people_ppe_or_procedure_actions_not_closi"
      },
      {
        "label": "How often it happens, in a number",
        "value": "how_often_it_happens_in_a_number"
      },
      {
        "label": "Who sees it happen, by role",
        "value": "who_sees_it_happen_by_role"
      },
      {
        "label": "Evidence they can show: a log, an incident, footage",
        "value": "evidence_they_can_show_a_log_an_incident_footage"
      }
    ],
    "ways": {
      "open": [
        "What's the one thing on site that keeps coming back no matter what you do?",
        "How often does that happen in a typical month?"
      ],
      "label": [
        "It seems like this has been going on for a while.",
        "It sounds like everyone knows about it but nobody owns it."
      ],
      "noOriented": [
        "Would it be wrong to say this is more about people near vehicles than PPE?"
      ],
      "mirror": [
        "They say \"it's mostly the forklifts\" → \"The forklifts?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So it's pedestrians crossing the forklift lane at shift change, roughly a near-hit every two days, and the supervisors see it but can't stop it. That's right?"
      ]
    },
    "listenFor": "Vehicles near people came up at 57 accounts in 2026; PPE and procedure at 48; actions not closing at 34; ergonomics at 31.",
    "redFlag": "We described the problem and they nodded. The words on the record are ours.",
    "whyClose": ""
  },
  {
    "n": 12,
    "topic": "The problem",
    "question": "Why does it keep happening?",
    "why": "Decides whether we're the right answer at all. If people can't watch it 24/7, we fix it. If nobody acts on what they already know, we don't.",
    "whoToAsk": [
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_why_status",
    "detailsProperty": "da_why_details",
    "properties": [
      "da_why_status",
      "da_why_notes",
      "da_why_source",
      "da_why_details",
      "da_why_root_cause"
    ],
    "details": [
      {
        "label": "The reason, in their words: coverage, capacity to act, accountability, data scattered, or controls bypassed",
        "value": "the_reason_in_their_words_coverage_capacity_to_act_accountability_data_scattered"
      },
      {
        "label": "How it came to be this way (cameras bought for security, team cut, acquisition)",
        "value": "how_it_came_to_be_this_way_cameras_bought_for_security_team_cut_acquisition"
      },
      {
        "label": "One other explanation they've ruled out, and why",
        "value": "one_other_explanation_they_ve_ruled_out_and_why"
      }
    ],
    "ways": {
      "open": [
        "What do you think is really behind it?",
        "Where you lack insight, is it the systems, the skills, or the data just doesn't exist?",
        "What else could explain it, and why isn't it that?"
      ],
      "label": [
        "It sounds like the rules are clear. It's watching them that's hard.",
        "It seems like people know what to do when someone's looking."
      ],
      "noOriented": [
        "Is it unfair to say this is more about not being able to see it than about people not caring?"
      ],
      "mirror": [
        "They say \"it's a culture thing\" → \"A culture thing?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So the procedure's fine, the supervisors are on production first, and nobody can cover nights. It's coverage, not attitude. That's right?"
      ]
    },
    "listenFor": "Capacity is the cause buyers name most: 'That frontline becomes the capacity bottleneck' (Munters).",
    "redFlag": "Accountability: they know and nobody acts. We'd be selling data into an organisation that ignores its data.",
    "whyClose": "Root cause is the field most often missing from records that otherwise look complete."
  },
  {
    "n": 13,
    "topic": "The problem",
    "question": "Would more people fix it, and would they pay for them?",
    "why": "Tells you whether you're competing with headcount on price, or whether headcount is the cost you replace.",
    "whoToAsk": [
      "Group EHS lead",
      "Finance or risk"
    ],
    "industry": "All",
    "key": false,
    "theirWords": true,
    "weight": 2.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_headcount_status",
    "detailsProperty": "da_headcount_details",
    "properties": [
      "da_headcount_status",
      "da_headcount_notes",
      "da_headcount_source",
      "da_headcount_details"
    ],
    "details": [
      {
        "label": "Answer to 'would ten more safety officers solve it?'",
        "value": "answer_to_would_ten_more_safety_officers_solve_it"
      },
      {
        "label": "Answer to 'would you fund them?'",
        "value": "answer_to_would_you_fund_them"
      },
      {
        "label": "What that headcount would cost, in their numbers",
        "value": "what_that_headcount_would_cost_in_their_numbers"
      }
    ],
    "ways": {
      "open": [
        "If you had ten more safety officers tomorrow, would this be solved?",
        "And would anyone fund them?"
      ],
      "label": [
        "It sounds like the answer is more people, and that's off the table."
      ],
      "noOriented": [
        "Would it be crazy to compare this with the cost of hiring?"
      ],
      "mirror": [
        "They say \"we've asked for headcount before\" → \"Asked before?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So more people would help, nobody will fund them, and you'd need about four per site. That's where you are?"
      ]
    },
    "listenFor": "'I could hire two more safety specialists' (Munters). Four safety staff at ~£248k per site (Compleat Food).",
    "redFlag": "More people would fix it and the money is there: you're competing with headcount on price.",
    "whyClose": ""
  },
  {
    "n": 14,
    "topic": "The problem",
    "question": "What have they already tried, and why didn't it stick?",
    "why": "Someone who has spent money and been let down wants it fixed. It also stops us pitching what they abandoned two years ago.",
    "whoToAsk": [
      "Group EHS lead",
      "Site EHS manager"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_tried_status",
    "detailsProperty": "da_tried_details",
    "properties": [
      "da_tried_status",
      "da_tried_notes",
      "da_tried_source",
      "da_tried_details"
    ],
    "details": [
      {
        "label": "Training, signs, floor markings, speed limits",
        "value": "training_signs_floor_markings_speed_limits"
      },
      {
        "label": "More supervisors or safety staff",
        "value": "more_supervisors_or_safety_staff"
      },
      {
        "label": "EHS software and what it does or doesn't do",
        "value": "ehs_software_and_what_it_does_or_doesn_t_do"
      },
      {
        "label": "Previous camera or AI pilots: who, what happened, why it stopped",
        "value": "previous_camera_or_ai_pilots_who_what_happened_why_it_stopped"
      },
      {
        "label": "What is still running today",
        "value": "what_is_still_running_today"
      }
    ],
    "ways": {
      "open": [
        "What have you already tried for this?",
        "What happened with that?"
      ],
      "label": [
        "It sounds like you've been burned by a pilot before.",
        "It seems like the training works for a few weeks and then fades."
      ],
      "noOriented": [
        "Have you given up on technology fixing this?"
      ],
      "mirror": [
        "They say \"we tried a camera system once\" → \"Tried once?\""
      ],
      "accusationAudit": [
        "You're probably expecting another vendor who promises the world and drowns you in alerts."
      ],
      "summary": [
        "So training fades, the last camera pilot buried you in alerts, and the EHS system records things but doesn't watch anything. That's right?"
      ]
    },
    "listenFor": "Earlier vision trials 'died at roughly 60 percent and polluted their KPI system'. Free pilots from Intenseye and Voxel are common.",
    "redFlag": "A rival is already piloting somewhere stronger in the group (we are losing Nestlé US this way).",
    "whyClose": "Prior failed attempts are the strongest sign they want it fixed (Workbench)."
  },
  {
    "n": 15,
    "topic": "The problem",
    "question": "How aware are they, and who agrees there's a problem?",
    "why": "A thin record means different things at different stages. Agreement only counts if two people say it, including whoever owns the number.",
    "whoToAsk": [
      "Group EHS lead",
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": false,
    "theirWords": true,
    "weight": 2.0,
    "needed": [
      1,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_aware_status",
    "detailsProperty": "da_aware_details",
    "properties": [
      "da_aware_status",
      "da_aware_notes",
      "da_aware_source",
      "da_aware_details",
      "da_aware_awareness"
    ],
    "details": [
      {
        "label": "Where they are: not yet aware / aware / comparing options",
        "value": "where_they_are_not_yet_aware_aware_comparing_options"
      },
      {
        "label": "The line they said that shows it",
        "value": "the_line_they_said_that_shows_it"
      },
      {
        "label": "Who volunteered the problem with a number, and whether the owner of the number agrees",
        "value": "who_volunteered_the_problem_with_a_number_and_whether_the_owner_of_the_number_ag"
      }
    ],
    "ways": {
      "open": [
        "What made you take this call?",
        "What does your boss think about this?"
      ],
      "label": [
        "It sounds like this is on your radar more than your leadership's."
      ],
      "noOriented": [
        "Would it be wrong to say leadership doesn't see this as a problem yet?"
      ],
      "mirror": [
        "They say \"we're just exploring\" → \"Just exploring?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So you see it, the site leads see it, but the COO thinks the numbers are fine. That's right?"
      ]
    },
    "listenFor": "Not yet aware: 'already clean safety record'. Aware: 'probably 50 percent… go unreported'. Comparing: a requirements document or a three-vendor matrix.",
    "redFlag": "We described the problem and they nodded. Wording that matches our pitch counts as nothing.",
    "whyClose": ""
  },
  {
    "n": 16,
    "topic": "Business impact",
    "question": "Which number does it hurt, and whose number is it?",
    "why": "A problem nobody is measured on doesn't get funded. This finds the owner and the gap between today and target.",
    "whoToAsk": [
      "Group EHS lead",
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      3,
      3
    ],
    "statusProperty": "da_number_status",
    "detailsProperty": "da_number_details",
    "properties": [
      "da_number_status",
      "da_number_notes",
      "da_number_source",
      "da_number_details",
      "da_number_metric",
      "da_number_current_value",
      "da_number_target_value"
    ],
    "details": [
      {
        "label": "The metric: recordables, lost time, serious-injury potential, claims cost, a board target",
        "value": "the_metric_recordables_lost_time_serious_injury_potential_claims_cost_a_board_ta"
      },
      {
        "label": "Today's value and the target",
        "value": "today_s_value_and_the_target"
      },
      {
        "label": "The person who owns it",
        "value": "the_person_who_owns_it"
      },
      {
        "label": "What happens if they miss it, in their words",
        "value": "what_happens_if_they_miss_it_in_their_words"
      }
    ],
    "ways": {
      "open": [
        "What number are you held to, and by when?",
        "What happens if that number isn't hit?"
      ],
      "label": [
        "It sounds like that target came from above.",
        "It seems like you're on the hook for it personally."
      ],
      "noOriented": [
        "Would it be unfair to say last year's number went the wrong way?"
      ],
      "mirror": [
        "They say \"the board wants it down\" → \"Wants it down?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So you're at an LTIFR of 1.9, the board has committed to 1.4 by next year, and it's your name on it. That's right?"
      ]
    },
    "listenFor": "'Safety have a goal to deliver 5–10% reduction in LTI this year, last year saw an 8% increase' (FedEx EU). Audit scores and training completion: no buyer has named these.",
    "redFlag": "No owner, or a target nobody can state.",
    "whyClose": "A quantified metric at Stage 2 is one of the five gates that predict a win."
  },
  {
    "n": 17,
    "topic": "Business impact",
    "question": "Which business priority does it ladder to?",
    "why": "Executives fund their own priorities, not safety for its own sake. This finds the one they already care about.",
    "whoToAsk": [
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      3,
      3
    ],
    "statusProperty": "da_priority_status",
    "detailsProperty": "da_priority_details",
    "properties": [
      "da_priority_status",
      "da_priority_notes",
      "da_priority_source",
      "da_priority_details",
      "da_priority_business_priority"
    ],
    "details": [
      {
        "label": "The business priority it hits: [M] downtime, serious-injury and regulatory exposure, plant insurance cost, standards across plants · [L] contract retention, claims against margin, labour, exposure across sites · [R] claims and loss ratio, labour turnover, brand incidents, standards across stores",
        "value": "the_business_priority_it_hits_m_downtime_serious_injury_and_regulatory_exposure"
      },
      {
        "label": "Whether the person who owns that priority said so themselves",
        "value": "whether_the_person_who_owns_that_priority_said_so_themselves"
      },
      {
        "label": "Their target, and the payback they need",
        "value": "their_target_and_the_payback_they_need"
      },
      {
        "label": "What they're already spending against it some other way",
        "value": "what_they_re_already_spending_against_it_some_other_way"
      }
    ],
    "ways": {
      "open": [
        "What's the operating priority this year that this would help with?",
        "What else are you spending against that number?"
      ],
      "label": [
        "It sounds like downtime gets more attention upstairs than safety does."
      ],
      "noOriented": [
        "Would it be a bad idea to frame this around output rather than safety?"
      ],
      "mirror": [
        "They say \"it's really about consistency across plants\" → \"Consistency?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So the COO cares about consistency across plants, needs payback inside a year, and is already funding a standards programme. That's the priority?"
      ]
    },
    "listenFor": "'Safety is the hook in, operations is the meat' (DHL CIO). 'It has to be a stacked win' (UPS).",
    "redFlag": "It ties to no business priority: real, but not fundable.",
    "whyClose": ""
  },
  {
    "n": 18,
    "topic": "Business impact",
    "question": "What does it cost them, on their own numbers?",
    "why": "The business case has to be their arithmetic. Buyers reject our averages.",
    "whoToAsk": [
      "Finance or risk",
      "Ops or plant leader"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      3,
      3
    ],
    "statusProperty": "da_cost_status",
    "detailsProperty": "da_cost_details",
    "properties": [
      "da_cost_status",
      "da_cost_notes",
      "da_cost_source",
      "da_cost_details",
      "da_cost_cost_per_recordable_their_figure",
      "da_cost_share_of_inputs_buyer_stated"
    ],
    "details": [
      {
        "label": "Cost per recordable, direct and indirect, on their numbers",
        "value": "cost_per_recordable_direct_and_indirect_on_their_numbers"
      },
      {
        "label": "Downtime or output lost",
        "value": "downtime_or_output_lost"
      },
      {
        "label": "Hours spent on observations, investigations and safety reporting",
        "value": "hours_spent_on_observations_investigations_and_safety_reporting"
      },
      {
        "label": "Insurance: premium, deductible, renewal movement",
        "value": "insurance_premium_deductible_renewal_movement"
      },
      {
        "label": "Damage to racking, vehicles and product",
        "value": "damage_to_racking_vehicles_and_product"
      },
      {
        "label": "Fines and regulator response",
        "value": "fines_and_regulator_response"
      },
      {
        "label": "Absence cover and turnover",
        "value": "absence_cover_and_turnover"
      },
      {
        "label": "Share of these figures the buyer gave us (aim for 60%+)",
        "value": "share_of_these_figures_the_buyer_gave_us_aim_for_60"
      }
    ],
    "ways": {
      "open": [
        "What does a recordable cost you, all in?",
        "How many hours a week go into observations and building safety reports?"
      ],
      "label": [
        "It sounds like the real cost is bigger than what shows up in claims."
      ],
      "noOriented": [
        "Would you be against using your own figures rather than industry averages?"
      ],
      "mirror": [
        "They say \"claims are only part of it\" → \"Only part?\""
      ],
      "accusationAudit": [
        "You may be expecting us to throw a big ROI number at you that nobody internally will believe."
      ],
      "summary": [
        "So each recordable runs about £40k direct and the same again indirect, and your team spends a day a week on reports. That's right?"
      ]
    },
    "listenFor": "'The actual cost of workplace injuries… is estimated at £335k per year' (Compleat Food). 'Theoretical models may not reflect practical reality' (Actylis).",
    "redFlag": "Most inputs are ours. Under 60% buyer-stated means it's our case, not theirs.",
    "whyClose": ""
  },
  {
    "n": 19,
    "topic": "Business impact",
    "question": "Why now?",
    "why": "Stable problems don't create deadlines. A date they're organising around is what turns interest into a decision.",
    "whoToAsk": [
      "Group EHS lead",
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_now_status",
    "detailsProperty": "da_now_details",
    "properties": [
      "da_now_status",
      "da_now_notes",
      "da_now_source",
      "da_now_details",
      "da_now_compelling_date",
      "da_now_who_set_it"
    ],
    "details": [
      {
        "label": "The date, and what happens on it",
        "value": "the_date_and_what_happens_on_it"
      },
      {
        "label": "Who set it (board, client, regulator, insurer, audit)",
        "value": "who_set_it_board_client_regulator_insurer_audit"
      },
      {
        "label": "Open regulator notices or a recent serious incident",
        "value": "open_regulator_notices_or_a_recent_serious_incident"
      },
      {
        "label": "Governance calendar: board safety review, audit, insurance renewal",
        "value": "governance_calendar_board_safety_review_audit_insurance_renewal"
      }
    ],
    "ways": {
      "open": [
        "What happens if this isn't in place by then?",
        "What changed that makes this worth looking at now?"
      ],
      "label": [
        "It sounds like the incident in March changed the conversation."
      ],
      "noOriented": [
        "Would it be wrong to say this can wait until next year?"
      ],
      "mirror": [
        "They say \"before the renewal\" → \"Before the renewal?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So the insurer renews in March, the board reviews safety in February, and you need a story before both. That's the deadline?"
      ]
    },
    "listenFor": "A date someone else set: board target, contract renewal, insurer, regulator. Most triggers are incidents.",
    "redFlag": "A date we proposed. 'Why now' blank is a Win-Loss red flag.",
    "whyClose": "Only 22% of new-business deals had a 'why now' at Stage 2; it's one of the two gates that most separate wins."
  },
  {
    "n": 20,
    "topic": "The future they want",
    "question": "What does good look like, and by when?",
    "why": "Turns 'improve safety' into a condition with a number and a date that a pilot can be judged against.",
    "whoToAsk": [
      "Group EHS lead",
      "Site EHS manager"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_good_status",
    "detailsProperty": "da_good_details",
    "properties": [
      "da_good_status",
      "da_good_notes",
      "da_good_source",
      "da_good_details"
    ],
    "details": [
      {
        "label": "The target, with a unit and a date, against today's figure",
        "value": "the_target_with_a_unit_and_a_date_against_today_s_figure"
      },
      {
        "label": "How much of the floor they want visible, and by when",
        "value": "how_much_of_the_floor_they_want_visible_and_by_when"
      },
      {
        "label": "What they'll be able to do that they can't today",
        "value": "what_they_ll_be_able_to_do_that_they_can_t_today"
      },
      {
        "label": "Who will use it, by role",
        "value": "who_will_use_it_by_role"
      }
    ],
    "ways": {
      "open": [
        "If this works, what's different in six months?",
        "What would you be able to do that you can't today?"
      ],
      "label": [
        "It sounds like being able to prove a control worked matters more than more data."
      ],
      "noOriented": [
        "Would it be unrealistic to aim for a 20% drop on the pilot line?"
      ],
      "mirror": [
        "They say \"we just want to see it\" → \"See it?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So good is 20% fewer interactions on the dock by June, and being able to show the COO that the changes stuck. That's right?"
      ]
    },
    "listenFor": "'Not only data in, but data out, meaning proof the reduction also' (Munters).",
    "redFlag": "No number or no date: nothing to judge the pilot against.",
    "whyClose": ""
  },
  {
    "n": 21,
    "topic": "The future they want",
    "question": "How will they know it worked, and who says so?",
    "why": "Deals without written success criteria give the customer an easy way out at renewal.",
    "whoToAsk": [
      "Group EHS lead",
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      3
    ],
    "statusProperty": "da_proof_status",
    "detailsProperty": "da_proof_details",
    "properties": [
      "da_proof_status",
      "da_proof_notes",
      "da_proof_source",
      "da_proof_details"
    ],
    "details": [
      {
        "label": "Two or three measures for 90 days and 12 months, with baselines",
        "value": "two_or_three_measures_for_90_days_and_12_months_with_baselines"
      },
      {
        "label": "Who declares success",
        "value": "who_declares_success"
      },
      {
        "label": "What happens if the pilot passes",
        "value": "what_happens_if_the_pilot_passes"
      },
      {
        "label": "Pass or fail conditions: accuracy, relevance, sites, dates",
        "value": "pass_or_fail_conditions_accuracy_relevance_sites_dates"
      }
    ],
    "ways": {
      "open": [
        "In 90 days, which two or three numbers tell you it worked?",
        "Who signs off that it worked, and what happens next if it did?"
      ],
      "label": [
        "It sounds like the COO will judge this on a different number from you."
      ],
      "noOriented": [
        "Would it be a bad idea to write those down together now?"
      ],
      "mirror": [
        "They say \"we'll know it when we see it\" → \"When you see it?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So in 90 days you want dock interactions down 25% from about 100, the COO signs off, and if it passes you roll to two more sites. That's the deal?"
      ]
    },
    "listenFor": "Cencora: ergonomic events down 25% in 90 days from 100; injuries down 10% in 180 days from 14. Sonoco: '95%+ detection accuracy'.",
    "redFlag": "No success criteria by Vendor Selection. One AE had a success plan on 1 of 13 accounts.",
    "whyClose": "Agreed success measures are part of the close model."
  },
  {
    "n": 22,
    "topic": "The future they want",
    "question": "How much can their team actually act on?",
    "why": "Volume, not detection, is what stalls live accounts. Set the bar before go-live, not after.",
    "whoToAsk": [
      "Site EHS manager",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_load_status",
    "detailsProperty": "da_load_details",
    "properties": [
      "da_load_status",
      "da_load_notes",
      "da_load_source",
      "da_load_details",
      "da_load_events_per_week_they_can_act_on",
      "da_load_relevance_bar"
    ],
    "details": [
      {
        "label": "Events per week the team can review and act on",
        "value": "events_per_week_the_team_can_review_and_act_on"
      },
      {
        "label": "Share that must be relevant for them to keep using it",
        "value": "share_that_must_be_relevant_for_them_to_keep_using_it"
      },
      {
        "label": "Who acts, and when in the week",
        "value": "who_acts_and_when_in_the_week"
      }
    ],
    "ways": {
      "open": [
        "How many events a week could your team realistically act on?",
        "What share of alerts would need to be worth looking at for people to keep opening it?"
      ],
      "label": [
        "It sounds like a flood of alerts would kill this faster than anything."
      ],
      "noOriented": [
        "Would it be wrong to start with fewer rules and grow from there?"
      ],
      "mirror": [
        "They say \"we can't review hundreds\" → \"Hundreds?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So 30 events a week, at least 80% worth looking at, reviewed in the Monday huddle. That's the bar?"
      ]
    },
    "listenFor": "Munters set about 80% relevance. Linde's criteria are 'noise reduction and event relevance'.",
    "redFlag": "No number: expect inaction after go-live.",
    "whyClose": ""
  },
  {
    "n": 23,
    "topic": "The future they want",
    "question": "Is it worth it on their maths?",
    "why": "The honest number: today's cost against the target, minus what the change costs them, including their own time.",
    "whoToAsk": [
      "Finance or risk",
      "Ops or plant leader"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      3,
      3
    ],
    "statusProperty": "da_worth_status",
    "detailsProperty": "da_worth_details",
    "properties": [
      "da_worth_status",
      "da_worth_notes",
      "da_worth_source",
      "da_worth_details",
      "da_worth_annual_value_their_numbers",
      "da_worth_first_year_cost_of_change"
    ],
    "details": [
      {
        "label": "Annual value of the change, in their currency",
        "value": "annual_value_of_the_change_in_their_currency"
      },
      {
        "label": "Full first-year cost: licence, IT effort, cameras, consultation, training, internal time",
        "value": "full_first_year_cost_licence_it_effort_cameras_consultation_training_internal_ti"
      },
      {
        "label": "Ratio of value to cost (aim for 3:1)",
        "value": "ratio_of_value_to_cost_aim_for_3_1"
      },
      {
        "label": "Anyone who takes on a new risk or workload if it goes in (HR, works council, Security, site GM)",
        "value": "anyone_who_takes_on_a_new_risk_or_workload_if_it_goes_in_hr_works_council_securi"
      }
    ],
    "ways": {
      "open": [
        "What would this need to return for it to be an easy yes?",
        "Who ends up doing extra work if this goes in?"
      ],
      "label": [
        "It sounds like the licence isn't the only cost you're weighing."
      ],
      "noOriented": [
        "Would it be crazy to include your team's time in the cost?"
      ],
      "mirror": [
        "They say \"it has to pay back\" → \"Pay back?\""
      ],
      "accusationAudit": [
        "You might be thinking this costs about as much as the injuries it prevents."
      ],
      "summary": [
        "So on your numbers it's about £600k a year of value against £150k all in, and the site GMs carry the review time. That's how you see it?"
      ]
    },
    "listenFor": "3:1 or better from their numbers.",
    "redFlag": "Below 1:1: 'That's equivalent to my total annual cost of injuries' (Compleat Food). Or someone whose consent is needed gets a new liability.",
    "whyClose": ""
  },
  {
    "n": 24,
    "topic": "People & power",
    "question": "Who's involved, and how wide is the deal?",
    "why": "Breadth is the strongest single predictor of a new-business win. Safety alone doesn't close.",
    "whoToAsk": [
      "From the CRM",
      "Champion"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      3,
      3
    ],
    "statusProperty": "da_who_status",
    "detailsProperty": "da_who_details",
    "properties": [
      "da_who_status",
      "da_who_notes",
      "da_who_source",
      "da_who_details",
      "num_associated_contacts"
    ],
    "details": [
      {
        "label": "An Operations or plant leader engaged",
        "value": "an_operations_or_plant_leader_engaged"
      },
      {
        "label": "IT or OT engaged",
        "value": "it_or_ot_engaged"
      },
      {
        "label": "Someone VP or above engaged",
        "value": "someone_vp_or_above_engaged"
      },
      {
        "label": "Finance or risk engaged",
        "value": "finance_or_risk_engaged"
      },
      {
        "label": "HR, legal or works council engaged",
        "value": "hr_legal_or_works_council_engaged"
      }
    ],
    "ways": {
      "open": [
        "Who else would care about this?",
        "Who would be upset if they heard about this last?"
      ],
      "label": [
        "It sounds like Operations hasn't been part of this yet."
      ],
      "noOriented": [
        "Would it be a bad idea to bring the plant manager in on the next call?"
      ],
      "mirror": [
        "They say \"I'll loop people in later\" → \"Later?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So so far it's you and the site lead, and Ops, IT and finance haven't seen it. That's where we are?"
      ]
    },
    "listenFor": "Wins: Ops on 48% vs 19% of losses, IT 34% vs 6%, VP+ 72% vs 46%.",
    "redFlag": "Two or fewer people: new-business deals win 4–6% whatever else is true.",
    "whyClose": "NB win rate rises from 4.8% at 0–1 contacts to 66% at 8+."
  },
  {
    "n": 25,
    "topic": "People & power",
    "question": "Who signs, and have we met them?",
    "why": "Naming the signer doesn't move the odds. Meeting and aligning with them does.",
    "whoToAsk": [
      "Exec sponsor (COO / CFO / VP)",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      1,
      2,
      3,
      3
    ],
    "statusProperty": "da_signer_status",
    "detailsProperty": "da_signer_details",
    "properties": [
      "da_signer_status",
      "da_signer_notes",
      "da_signer_source",
      "da_signer_details",
      "economic_buyer_job_title",
      "met_with_economic_buyer"
    ],
    "details": [
      {
        "label": "Name and title of whoever signs above pilot scale",
        "value": "name_and_title_of_whoever_signs_above_pilot_scale"
      },
      {
        "label": "Whether they own a multi-site budget",
        "value": "whether_they_own_a_multi_site_budget"
      },
      {
        "label": "Whether we have met them on this, and what they said",
        "value": "whether_we_have_met_them_on_this_and_what_they_said"
      },
      {
        "label": "Whose budget this comes from, and whether it exists this year",
        "value": "whose_budget_this_comes_from_and_whether_it_exists_this_year"
      },
      {
        "label": "Budget cycle and approval thresholds",
        "value": "budget_cycle_and_approval_thresholds"
      }
    ],
    "ways": {
      "open": [
        "Who signs off a rollout across sites?",
        "What would they need to see to say yes?"
      ],
      "label": [
        "It sounds like the budget sits with Operations, not safety."
      ],
      "noOriented": [
        "Would it be wrong to ask for 20 minutes with them before the pilot?"
      ],
      "mirror": [
        "They say \"she'll want the numbers\" → \"The numbers?\""
      ],
      "accusationAudit": [
        "You might feel we're trying to go over your head. We're not; we want you to walk in with their questions already answered."
      ],
      "summary": [
        "So the VP Operations signs, the money is in her budget not yours, and we haven't met her yet. That's right?"
      ]
    },
    "listenFor": "VP or above who owns a multi-site budget. 'A plant manager or site H&S manager cannot sign a multi-site deal.'",
    "redFlag": "A manager-level 'signer' (that's a champion, not a buyer). Budget locked: 'we've already locked down budgets for 2027'.",
    "whyClose": "Signer met and aligned wins 35% in NB vs 3% when only named; reaching the go/no-go meeting lifts win rate from 28% to 62%."
  },
  {
    "n": 26,
    "topic": "People & power",
    "question": "Who is selling for us when we're not in the room?",
    "why": "A champion who hasn't been tested is a coach. Test by what they do, not what they say.",
    "whoToAsk": [
      "Champion"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_champion_status",
    "detailsProperty": "da_champion_details",
    "properties": [
      "da_champion_status",
      "da_champion_notes",
      "da_champion_source",
      "da_champion_details",
      "champion_s_"
    ],
    "details": [
      {
        "label": "Name, role, and who they report to",
        "value": "name_role_and_who_they_report_to"
      },
      {
        "label": "Something they've got approved before",
        "value": "something_they_ve_got_approved_before"
      },
      {
        "label": "Something they did for us between meetings (an introduction, internal data, a meeting set up)",
        "value": "something_they_did_for_us_between_meetings_an_introduction_internal_data_a_meeti"
      },
      {
        "label": "Something they warned us about that we didn't want to hear",
        "value": "something_they_warned_us_about_that_we_didn_t_want_to_hear"
      }
    ],
    "ways": {
      "open": [
        "How have you got something like this approved before?",
        "What will you say about this to your boss before we speak again?"
      ],
      "label": [
        "It sounds like you've done this before with other projects."
      ],
      "noOriented": [
        "Would it be unreasonable to ask you to set up the call with the plant manager?"
      ],
      "mirror": [
        "They say \"I'll push it internally\" → \"Push it?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So you got the last system approved through the capex committee, and you'll take the case to the VP on Tuesday. That's the plan?"
      ]
    },
    "listenFor": "A safety or EHS champion who has been tested wins 83% of the new-business deals where one is flagged.",
    "redFlag": "Champion has never done anything that cost them time or capital. A strong signer with a weak champion wins 0%.",
    "whyClose": "Strong signer and strong champion together win 49%; either alone wins 0%."
  },
  {
    "n": 27,
    "topic": "People & power",
    "question": "What does this mean for them personally?",
    "why": "People act on personal stakes. It also tells you what they'll defend if this gets hard.",
    "whoToAsk": [
      "Group EHS lead",
      "Site EHS manager",
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": false,
    "theirWords": true,
    "weight": 2.0,
    "needed": [
      1,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_personal_status",
    "detailsProperty": "da_personal_details",
    "properties": [
      "da_personal_status",
      "da_personal_notes",
      "da_personal_source",
      "da_personal_details"
    ],
    "details": [
      {
        "label": "What they personally risk if nothing changes",
        "value": "what_they_personally_risk_if_nothing_changes"
      },
      {
        "label": "What they gain if it works",
        "value": "what_they_gain_if_it_works"
      },
      {
        "label": "Their honest concern about this, in their words",
        "value": "their_honest_concern_about_this_in_their_words"
      },
      {
        "label": "Why this target and not a higher one, and who it's committed to (board, client, regulator)",
        "value": "why_this_target_and_not_a_higher_one_and_who_it_s_committed_to_board_client_regu"
      }
    ],
    "ways": {
      "open": [
        "What's your honest concern here?",
        "Why that target and not a higher one?"
      ],
      "label": [
        "It sounds like this lands on you if something goes wrong.",
        "It seems like you've been asked to fix this rather than chose to."
      ],
      "noOriented": [
        "Would it be wrong to say this could be a career-defining project for you?"
      ],
      "mirror": [
        "They say \"it's on my objectives\" → \"Your objectives?\""
      ],
      "accusationAudit": [
        "You may be worried this becomes another thing that's judged a failure with your name on it."
      ],
      "summary": [
        "So the target came from the board, you own it, and the worry is a pilot that doesn't prove anything. That's right?"
      ]
    },
    "listenFor": "'Worried the program will be judged a failure with personal accountability for him' (ABF Sugar).",
    "redFlag": "A motivation we suggested and they agreed to. It won't survive a competitor who asks properly.",
    "whyClose": ""
  },
  {
    "n": 28,
    "topic": "People & power",
    "question": "Who could say no, and what would change their mind?",
    "why": "Silent stakeholders with a veto stall deals that look healthy. Find them while there's time.",
    "whoToAsk": [
      "Group EHS lead",
      "Champion"
    ],
    "industry": "All",
    "key": false,
    "theirWords": false,
    "weight": 2.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_veto_status",
    "detailsProperty": "da_veto_details",
    "properties": [
      "da_veto_status",
      "da_veto_notes",
      "da_veto_source",
      "da_veto_details"
    ],
    "details": [
      {
        "label": "Each person who can block it: IT, AI committee, Security, union or works council, HR, legal, procurement",
        "value": "each_person_who_can_block_it_it_ai_committee_security_union_or_works_council_hr"
      },
      {
        "label": "What each needs to say yes",
        "value": "what_each_needs_to_say_yes"
      },
      {
        "label": "Anyone who takes on a new risk if this goes in",
        "value": "anyone_who_takes_on_a_new_risk_if_this_goes_in"
      },
      {
        "label": "Any disagreement between buyers on the target, the baseline, the signer or the date",
        "value": "any_disagreement_between_buyers_on_the_target_the_baseline_the_signer_or_the_dat"
      }
    ],
    "ways": {
      "open": [
        "Who could stop this, even if everyone else wants it?",
        "What would they need to hear?"
      ],
      "label": [
        "It sounds like legal could slow this down."
      ],
      "noOriented": [
        "Would it be a mistake to talk to HR before the pilot is agreed?"
      ],
      "mirror": [
        "They say \"procurement can be tricky\" → \"Tricky?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So IT, the works council and procurement can each say no, and the works council meets quarterly. That's the list?"
      ]
    },
    "listenFor": "IT and AI committees, Security, unions and works councils, HR and legal.",
    "redFlag": "Two buyers disagree on the target, baseline, signer or date, and it's unresolved.",
    "whyClose": ""
  },
  {
    "n": 29,
    "topic": "How they'll buy",
    "question": "How will they decide?",
    "why": "If they're already comparing options against criteria, find out who wrote them while they can still change.",
    "whoToAsk": [
      "Group EHS lead",
      "IT / OT",
      "Finance or risk"
    ],
    "industry": "All",
    "key": false,
    "theirWords": false,
    "weight": 2.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_decide_status",
    "detailsProperty": "da_decide_details",
    "properties": [
      "da_decide_status",
      "da_decide_notes",
      "da_decide_source",
      "da_decide_details"
    ],
    "details": [
      {
        "label": "The criteria, how much each weighs, and who owns each one",
        "value": "the_criteria_how_much_each_weighs_and_who_owns_each_one"
      },
      {
        "label": "Whether the criteria came from them or from another vendor",
        "value": "whether_the_criteria_came_from_them_or_from_another_vendor"
      },
      {
        "label": "Where we win a high-weighted criterion, and where we lose one",
        "value": "where_we_win_a_high_weighted_criterion_and_where_we_lose_one"
      }
    ],
    "ways": {
      "open": [
        "How will you choose between the options?",
        "Who wrote those criteria, and what problem were they written to solve?"
      ],
      "label": [
        "It sounds like the criteria came from another vendor's demo."
      ],
      "noOriented": [
        "Would it be wrong to add relevance of alerts to the list?"
      ],
      "mirror": [
        "They say \"accuracy is the main thing\" → \"The main thing?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So it's accuracy, privacy and price, weighted in that order, and IT owns the first two. That's the scorecard?"
      ]
    },
    "listenFor": "Criteria with weights and owners. Linde's: 'noise reduction and event relevance'.",
    "redFlag": "Weaker than a rival on a high-weighted criterion: reposition or walk, don't discount.",
    "whyClose": ""
  },
  {
    "n": 30,
    "topic": "How they'll buy",
    "question": "What happens between 'yes' and a signature?",
    "why": "Most late losses are stalls. Every step with an owner and a duration is a step that can't surprise you.",
    "whoToAsk": [
      "Group EHS lead",
      "Finance or risk"
    ],
    "industry": "All",
    "key": false,
    "theirWords": false,
    "weight": 2.0,
    "needed": [
      0,
      0,
      1,
      2,
      3
    ],
    "statusProperty": "da_steps_status",
    "detailsProperty": "da_steps_details",
    "properties": [
      "da_steps_status",
      "da_steps_notes",
      "da_steps_source",
      "da_steps_details"
    ],
    "details": [
      {
        "label": "Every step: legal, procurement, security review, AI committee, works council, capex approval, each with an owner and duration",
        "value": "every_step_legal_procurement_security_review_ai_committee_works_council_capex_ap"
      },
      {
        "label": "Whether we need to be a preferred vendor or sign an MSA",
        "value": "whether_we_need_to_be_a_preferred_vendor_or_sign_an_msa"
      },
      {
        "label": "Days of steps vs days to their deadline",
        "value": "days_of_steps_vs_days_to_their_deadline"
      },
      {
        "label": "Any step type still unknown",
        "value": "any_step_type_still_unknown"
      }
    ],
    "ways": {
      "open": [
        "Walk me through every step from 'yes' to a signed PO.",
        "Which of those can start now?"
      ],
      "label": [
        "It sounds like procurement has its own timeline."
      ],
      "noOriented": [
        "Would it be a bad idea to start the security review in parallel?"
      ],
      "mirror": [
        "They say \"then it goes to legal\" → \"To legal?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So legal takes three weeks, procurement two, security runs in parallel, and that still lands before the March renewal. That's the path?"
      ]
    },
    "listenFor": "Owners and durations for every step. 'Legal is reviewing' is not a returned redline.",
    "redFlag": "Any step still 'unknown' after a verbal yes.",
    "whyClose": "Unresponsive, postponed and timing losses are 53% of new-business losses."
  },
  {
    "n": 31,
    "topic": "How they'll buy",
    "question": "Where does it start, and where does it go?",
    "why": "A pilot at the easiest site lands and then stalls. Choose a site that proves something to whoever signs the rollout.",
    "whoToAsk": [
      "Group EHS lead",
      "Ops or plant leader",
      "Exec sponsor (COO / CFO / VP)"
    ],
    "industry": "All",
    "key": false,
    "theirWords": false,
    "weight": 2.0,
    "needed": [
      0,
      0,
      2,
      2,
      3
    ],
    "statusProperty": "da_scope_status",
    "detailsProperty": "da_scope_details",
    "properties": [
      "da_scope_status",
      "da_scope_notes",
      "da_scope_source",
      "da_scope_details",
      "number_of_sites_to_start",
      "number_of_sites_for_expansion_potential"
    ],
    "details": [
      {
        "label": "Pilot site and why it was chosen",
        "value": "pilot_site_and_why_it_was_chosen"
      },
      {
        "label": "Areas, cameras and risks in and out of scope",
        "value": "areas_cameras_and_risks_in_and_out_of_scope"
      },
      {
        "label": "What would justify a rollout, in their words",
        "value": "what_would_justify_a_rollout_in_their_words"
      },
      {
        "label": "Rollout sites, sequence and timing",
        "value": "rollout_sites_sequence_and_timing"
      },
      {
        "label": "Whether the signer can approve the rollout at that scale",
        "value": "whether_the_signer_can_approve_the_rollout_at_that_scale"
      }
    ],
    "ways": {
      "open": [
        "Which site should go first, and why that one?",
        "What would you need to see to roll out to the rest?"
      ],
      "label": [
        "It sounds like the pilot site is the easiest one, not the most representative."
      ],
      "noOriented": [
        "Would it be wrong to pick the site the VP worries about most?"
      ],
      "mirror": [
        "They say \"then we'll see\" → \"Then you'll see?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So the pilot is Leeds because it has the worst numbers, and if it hits target the VP rolls out to five more sites next year. That's the plan?"
      ]
    },
    "listenFor": "A representative site the signer cares about. A non-union first site can help.",
    "redFlag": "A signer who can only approve one site.",
    "whyClose": ""
  },
  {
    "n": 32,
    "topic": "How they'll buy",
    "question": "How will the workforce, unions and privacy be handled?",
    "why": "The union or works council question decides whether the floor accepts it. Raise it early; it is usually solvable.",
    "whoToAsk": [
      "HR, legal or works council",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": true,
    "theirWords": true,
    "weight": 3.0,
    "needed": [
      1,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_workforce_status",
    "detailsProperty": "da_workforce_details",
    "properties": [
      "da_workforce_status",
      "da_workforce_notes",
      "da_workforce_source",
      "da_workforce_details"
    ],
    "details": [
      {
        "label": "Sites with a union or works council, what consultation requires, and how long",
        "value": "sites_with_a_union_or_works_council_what_consultation_requires_and_how_long"
      },
      {
        "label": "Whether findings will be used for coaching or discipline, and whether that's in writing",
        "value": "whether_findings_will_be_used_for_coaching_or_discipline_and_whether_that_s_in_w"
      },
      {
        "label": "Whether anyone expects to identify individuals",
        "value": "whether_anyone_expects_to_identify_individuals"
      },
      {
        "label": "Retention and viewing rules",
        "value": "retention_and_viewing_rules"
      },
      {
        "label": "Monitoring technology introduced before, and how it landed",
        "value": "monitoring_technology_introduced_before_and_how_it_landed"
      }
    ],
    "ways": {
      "open": [
        "If the floor heard about this tomorrow, what would the union or works council ask first?",
        "How will findings be used: coaching or discipline?"
      ],
      "label": [
        "It sounds like the last monitoring project didn't go down well."
      ],
      "noOriented": [
        "Would you be against committing in writing that this won't be used for discipline?"
      ],
      "mirror": [
        "They say \"the union will have questions\" → \"Questions?\""
      ],
      "accusationAudit": [
        "You're probably thinking this looks like surveillance, and that's exactly how it'll be heard on the floor."
      ],
      "summary": [
        "So three sites have a works council, consultation takes about six weeks, and a written non-disciplinary policy would settle most of it. That's right?"
      ]
    },
    "listenFor": "'Are you going to coach him or are you going to discipline him?' (UPS). A written memo 'won legal and union acceptance' (Cummins).",
    "redFlag": "They want individuals identified: walk away. A union contract bars camera AI and there's no other site to start.",
    "whyClose": ""
  },
  {
    "n": 33,
    "topic": "Competition & proof",
    "question": "What else are they considering?",
    "why": "The real competitor is often doing nothing, hiring, or the EHS platform's own AI.",
    "whoToAsk": [
      "Champion",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": false,
    "theirWords": false,
    "weight": 2.0,
    "needed": [
      0,
      1,
      2,
      2,
      2
    ],
    "statusProperty": "da_alternatives_status",
    "detailsProperty": "da_alternatives_details",
    "properties": [
      "da_alternatives_status",
      "da_alternatives_notes",
      "da_alternatives_source",
      "da_alternatives_details"
    ],
    "details": [
      {
        "label": "Other vendors being looked at or piloted anywhere in the group",
        "value": "other_vendors_being_looked_at_or_piloted_anywhere_in_the_group"
      },
      {
        "label": "Doing nothing, building in-house, or adding headcount",
        "value": "doing_nothing_building_in_house_or_adding_headcount"
      },
      {
        "label": "The EHS platform's own AI add-on",
        "value": "the_ehs_platform_s_own_ai_add_on"
      },
      {
        "label": "Anything a competitor has told them about us",
        "value": "anything_a_competitor_has_told_them_about_us"
      }
    ],
    "ways": {
      "open": [
        "What else are you looking at?",
        "What have other vendors told you to watch out for?"
      ],
      "label": [
        "It sounds like someone's already been in with a free pilot."
      ],
      "noOriented": [
        "Would it be wrong to assume another site in the group is already trialling something?"
      ],
      "mirror": [
        "They say \"we've seen a couple of others\" → \"A couple?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So Intenseye offered a free pilot, IT would rather build it, and doing nothing is still on the table. That's the field?"
      ]
    },
    "listenFor": "86 accounts named a vision vendor in 2026. Cority, Gensuite and Intelex now ship their own AI.",
    "redFlag": "A rival has a head start at a site with more internal pull.",
    "whyClose": ""
  },
  {
    "n": 34,
    "topic": "Competition & proof",
    "question": "What would make them sure?",
    "why": "Proof bars set after a failed pilot are specific. Know them before you design the pilot.",
    "whoToAsk": [
      "Exec sponsor (COO / CFO / VP)",
      "IT / OT",
      "Group EHS lead"
    ],
    "industry": "All",
    "key": false,
    "theirWords": false,
    "weight": 2.0,
    "needed": [
      0,
      0,
      1,
      2,
      2
    ],
    "statusProperty": "da_sure_status",
    "detailsProperty": "da_sure_details",
    "properties": [
      "da_sure_status",
      "da_sure_notes",
      "da_sure_source",
      "da_sure_details"
    ],
    "details": [
      {
        "label": "The risks they've stated, and the proof each needs",
        "value": "the_risks_they_ve_stated_and_the_proof_each_needs"
      },
      {
        "label": "Accuracy and relevance bar, and figures other vendors quoted",
        "value": "accuracy_and_relevance_bar_and_figures_other_vendors_quoted"
      },
      {
        "label": "Reference they'd trust: same industry, scale, union environment",
        "value": "reference_they_d_trust_same_industry_scale_union_environment"
      },
      {
        "label": "What happens to them if it fails",
        "value": "what_happens_to_them_if_it_fails"
      }
    ],
    "ways": {
      "open": [
        "What would make you sure?",
        "What accuracy have other vendors promised you?"
      ],
      "label": [
        "It sounds like you'll want to hear it from someone who's done it."
      ],
      "noOriented": [
        "Would a call with a customer in a unionised plant be a waste of your time?"
      ],
      "mirror": [
        "They say \"we need proof it works here\" → \"Here?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So you need 90% relevance on the dock, a reference in food manufacturing, and IT happy with the data flow. That's what proof looks like?"
      ]
    },
    "listenFor": "'Weekly weighted accuracy rate reporting' (Pirelli). Earlier trials died at about 60% accuracy.",
    "redFlag": "The reference they need doesn't exist.",
    "whyClose": ""
  },
  {
    "n": 35,
    "topic": "Momentum",
    "question": "What will they do next, and by when?",
    "why": "A next step on our calendar isn't progress. A next step on theirs, that costs them something, is.",
    "whoToAsk": [
      "Champion"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      2,
      2,
      2,
      2
    ],
    "statusProperty": "da_next_status",
    "detailsProperty": "da_next_details",
    "properties": [
      "da_next_status",
      "da_next_notes",
      "da_next_source",
      "da_next_details",
      "da_next_next_step_date"
    ],
    "details": [
      {
        "label": "The next thing they'll do, with a date",
        "value": "the_next_thing_they_ll_do_with_a_date"
      },
      {
        "label": "Commitments they've already made: an introduction upward, data they had to fetch, a site walk, a business case co-written, senior time booked",
        "value": "commitments_they_ve_already_made_an_introduction_upward_data_they_had_to_fetch_a"
      },
      {
        "label": "Whether the last thing they promised happened",
        "value": "whether_the_last_thing_they_promised_happened"
      }
    ],
    "ways": {
      "open": [
        "What's the next step on your side, and when?",
        "What would make it easy for you to get the VP in the room?"
      ],
      "label": [
        "It sounds like this is competing with a lot of other priorities this month."
      ],
      "noOriented": [
        "Would it be a bad idea to put the site walk in the diary now?"
      ],
      "mirror": [
        "They say \"I'll get back to you\" → \"Get back to me?\""
      ],
      "accusationAudit": [],
      "summary": [
        "So you'll send the injury log by Friday and introduce the plant manager next week. That's what happens next?"
      ]
    },
    "listenFor": "Any two commitments that cost them time or capital means they're on the journey with you.",
    "redFlag": "No next step, or no meeting in three weeks. Meetings and demos alone are the most common false positive.",
    "whyClose": "Unresponsive, postponed and timing losses are 53% of new-business losses."
  },
  {
    "n": 36,
    "topic": "Momentum",
    "question": "Is there anything that should stop us?",
    "why": "Losses are mostly stalls. These are the patterns that predicted them; each has a known fix or none.",
    "whoToAsk": [
      "Champion",
      "From the CRM"
    ],
    "industry": "All",
    "key": true,
    "theirWords": false,
    "weight": 3.0,
    "needed": [
      1,
      1,
      1,
      1,
      1
    ],
    "statusProperty": "da_stop_status",
    "detailsProperty": "da_stop_details",
    "properties": [
      "da_stop_status",
      "da_stop_notes",
      "da_stop_source",
      "da_stop_details",
      "da_stop_unresolved"
    ],
    "details": [
      {
        "label": "No route to a VP-level budget owner",
        "value": "no_route_to_a_vp_level_budget_owner"
      },
      {
        "label": "No cameras where the risk is",
        "value": "no_cameras_where_the_risk_is"
      },
      {
        "label": "A union bar with no other site to start",
        "value": "a_union_bar_with_no_other_site_to_start"
      },
      {
        "label": "Nobody with time to own it",
        "value": "nobody_with_time_to_own_it"
      },
      {
        "label": "A clean record and no Operations angle",
        "value": "a_clean_record_and_no_operations_angle"
      },
      {
        "label": "Licence cost out of scale with the site",
        "value": "licence_cost_out_of_scale_with_the_site"
      },
      {
        "label": "They don't act on what they already know",
        "value": "they_don_t_act_on_what_they_already_know"
      },
      {
        "label": "Budget locked or frozen",
        "value": "budget_locked_or_frozen"
      },
      {
        "label": "AI freeze, new AI committee, or a decision to build",
        "value": "ai_freeze_new_ai_committee_or_a_decision_to_build"
      },
      {
        "label": "They want individuals identified",
        "value": "they_want_individuals_identified"
      },
      {
        "label": "Outside our core industries and site sizes",
        "value": "outside_our_core_industries_and_site_sizes"
      }
    ],
    "ways": {
      "open": [
        "What could make this go quiet?",
        "What would have to be true for this not to happen this year?"
      ],
      "label": [
        "It sounds like budget might not be there until next year."
      ],
      "noOriented": [
        "Is it a bad idea to stop here if the budget's gone?"
      ],
      "mirror": [
        "They say \"it depends on budget\" → \"Depends on budget?\""
      ],
      "accusationAudit": [],
      "summary": []
    },
    "listenFor": "None, or each one ticked with its fix noted.",
    "redFlag": "Any ticked with no known fix: doesn't fit yet.",
    "whyClose": ""
  }
];

export const PERSONAS: Persona[] = [
  {
    "who": "Group EHS lead",
    "leads": [
      "Why does it keep happening?",
      "Would more people fix it, and would they pay for them?",
      "What have they already tried, and why didn't it stick?",
      "How aware are they, and who agrees there's a problem?",
      "Which number does it hurt, and whose number is it?",
      "Why now?",
      "What does good look like, and by when?",
      "How will they know it worked, and who says so?",
      "What does this mean for them personally?",
      "Who could say no, and what would change their mind?",
      "How will they decide?",
      "What happens between 'yes' and a signature?",
      "Where does it start, and where does it go?"
    ],
    "also": [
      "Where is the risk, and how much of it can they actually see today?",
      "What do they measure and report today?",
      "What happens after something is found?",
      "What do claims and turnover cost?",
      "What is actually going wrong, in their words?",
      "How much can their team actually act on?",
      "Who signs, and have we met them?",
      "How will the workforce, unions and privacy be handled?",
      "What else are they considering?",
      "What would make them sure?"
    ],
    "titles": {
      "L": "Group HSE Director, VP Health Safety & Compliance",
      "M": "Corporate EHS Director, VP EHS & Sustainability",
      "R": "Director of Safety & Risk, VP HSE"
    },
    "dontAsk": "Camera and network specifics. They will answer, and it will not count."
  },
  {
    "who": "Site EHS manager",
    "leads": [
      "Which sites are in scope, and what happens on them?",
      "Where is the risk, and how much of it can they actually see today?",
      "What do they measure and report today?",
      "What happens after something is found?",
      "What is actually going wrong, in their words?",
      "How much can their team actually act on?"
    ],
    "also": [
      "What have they already tried, and why didn't it stick?",
      "What does good look like, and by when?",
      "What does this mean for them personally?"
    ],
    "titles": {
      "L": "Site HSE Manager, Regional HSE Business Partner",
      "M": "Plant EHS Manager, Site Safety Engineer",
      "R": "DC Safety Manager, Regional Safety Manager"
    },
    "dontAsk": "Premium, loss ratio, budget, criteria weighting, signature authority. A guess here pollutes the record."
  },
  {
    "who": "Ops or plant leader",
    "leads": [
      "What does an incident cost the line?",
      "What's riding on client contracts?"
    ],
    "also": [
      "Which sites are in scope, and what happens on them?",
      "What does it cost them, on their own numbers?",
      "Is it worth it on their maths?",
      "Where does it start, and where does it go?"
    ],
    "titles": {
      "L": "Site GM, Regional Ops Director, VP Network Ops",
      "M": "Plant Manager, Director of Manufacturing",
      "R": "DC General Manager, VP Supply Chain"
    },
    "dontAsk": "Camera specifics, insurance, criteria weighting."
  },
  {
    "who": "Exec sponsor (COO / CFO / VP)",
    "leads": [
      "Which business priority does it ladder to?",
      "Who signs, and have we met them?",
      "What would make them sure?"
    ],
    "also": [
      "How aware are they, and who agrees there's a problem?",
      "Which number does it hurt, and whose number is it?",
      "Why now?",
      "How will they know it worked, and who says so?",
      "What does this mean for them personally?",
      "Where does it start, and where does it go?"
    ],
    "titles": {
      "L": "CFO, COO, VP Network Operations",
      "M": "COO, VP Manufacturing, Group Risk Director",
      "R": "CFO, VP Risk Management, COO"
    },
    "dontAsk": "Camera counts, network topology, shift patterns, observation completion. Asking wastes the scarcest access you have."
  },
  {
    "who": "IT / OT",
    "leads": [
      "Do their cameras see the risk?",
      "What will IT, security and data rules require?"
    ],
    "also": [
      "Who owns the cameras and the network?",
      "How will they decide?",
      "What would make them sure?"
    ],
    "titles": {
      "L": "Group IT, frequently an outsourced MSP",
      "M": "IT/OT Manager, Controls Engineering, Plant IT",
      "R": "Retail IT, Store Systems, DC Systems"
    },
    "dontAsk": "Business problem, impact, anchor, motivation."
  },
  {
    "who": "Security or camera owner",
    "leads": [
      "Who owns the cameras and the network?"
    ],
    "also": [
      "Do their cameras see the risk?"
    ],
    "titles": {
      "L": "Site Security, often the landlord or the client",
      "M": "Site Security Manager, Facilities",
      "R": "Loss Prevention / Asset Protection Director — a principal, not a gate"
    },
    "dontAsk": "Business problem in [M] and [L]. In [R] they are a mandatory source for it."
  },
  {
    "who": "Finance or risk",
    "leads": [
      "What do claims and turnover cost?",
      "What does it cost them, on their own numbers?",
      "Is it worth it on their maths?"
    ],
    "also": [
      "What does an incident cost the line?",
      "What's riding on client contracts?",
      "Would more people fix it, and would they pay for them?",
      "How will they decide?",
      "What happens between 'yes' and a signature?"
    ],
    "titles": {
      "L": "CFO, Group Risk Manager, Insurance Manager",
      "M": "Group Risk & Insurance, Captive Manager",
      "R": "VP Risk Management, Workers' Comp Manager — frequently the Exec too"
    },
    "dontAsk": "Camera specifics, shift patterns, observation mechanics."
  },
  {
    "who": "HR, legal or works council",
    "leads": [
      "How will the workforce, unions and privacy be handled?"
    ],
    "also": [],
    "titles": {
      "L": "HR Director, agency labour partner",
      "M": "Works Council, union convenor, Employee Relations",
      "R": "HR Business Partner, Labour Relations"
    },
    "dontAsk": "Impact arithmetic, camera specifics, criteria weighting."
  },
  {
    "who": "Champion",
    "leads": [
      "Who is selling for us when we're not in the room?",
      "What else are they considering?",
      "What will they do next, and by when?",
      "Is there anything that should stop us?"
    ],
    "also": [
      "Who's involved, and how wide is the deal?",
      "Who could say no, and what would change their mind?"
    ],
    "titles": {
      "L": "",
      "M": "",
      "R": ""
    },
    "dontAsk": ""
  },
  {
    "who": "From the CRM",
    "leads": [
      "Who's involved, and how wide is the deal?"
    ],
    "also": [
      "Is there anything that should stop us?"
    ],
    "titles": {
      "L": "",
      "M": "",
      "R": ""
    },
    "dontAsk": ""
  }
];

export const CLOSE_EVIDENCE: CloseEvidence[] = [
  {
    "signal": "3 or more people engaged",
    "from": "Who's involved: people engaged",
    "points": 10,
    "evidence": "Win rate climbs from 4.8% at 0–1 contacts to 66% at 8+; 3 is where the odds turn."
  },
  {
    "signal": "5 or more people engaged",
    "from": "Who's involved: people engaged",
    "points": 8,
    "evidence": "5+ is where new-business deals become likely to close."
  },
  {
    "signal": "Someone VP or above engaged",
    "from": "Who's involved: details checklist",
    "points": 10,
    "evidence": "Power on the deal lifts win rate from 5.6% to 18.6%; with breadth, 39%."
  },
  {
    "signal": "Signer met and aligned",
    "from": "Who signs: Confirmed",
    "points": 14,
    "evidence": "Signer met and aligned wins 35% vs 3% when only named."
  },
  {
    "signal": "Champion tested",
    "from": "Who is selling for us: Confirmed",
    "points": 14,
    "evidence": "Untested champion = no champion. Strong signer + weak champion wins 0%; both strong 49%."
  },
  {
    "signal": "IT engaged",
    "from": "Who's involved: details checklist",
    "points": 10,
    "evidence": "IT on 34% of wins vs 6% of losses."
  },
  {
    "signal": "Operations leader engaged",
    "from": "Who's involved: details checklist",
    "points": 8,
    "evidence": "Ops or plant leader on 48% of wins vs 19% of losses."
  },
  {
    "signal": "Why now, in their words",
    "from": "Why now: Answered",
    "points": 8,
    "evidence": "Only 22% of deals had a 'why now' at Stage 2; one of the two gates that most separate wins."
  },
  {
    "signal": "Number and owner known",
    "from": "Which number does it hurt: Answered",
    "points": 6,
    "evidence": "Deals meeting 4–5 qualification gates at Stage 2 win 30.7% vs 5.4% for 0–1."
  },
  {
    "signal": "Success measures agreed",
    "from": "How will they know it worked: Answered",
    "points": 6,
    "evidence": "No written success criteria gives customers an 'easy way out' at renewal."
  },
  {
    "signal": "Next step on their calendar",
    "from": "What will they do next: Answered",
    "points": 6,
    "evidence": "Unresponsive, postponed and timing losses are 53% of new-business losses."
  }
];
